### ISSUE TITLE
When do you plan to make the code public?

### ISSUE THREAD

**Issue by luisfredgs** [Aolius/OrdMatch#1]
Hello,
Thanks for sharing your study with us. When do you plan to make the code public?

**Comment by Aolius** [comment]
Dear sir/madam, 
I'm very sorry for the delay of the code release, since I had a new unpublished paper which reused much of the same code. Luckily, the new paper was accepted very recently, so I'll release the unified code together. Please wait for several days. Thank you for your understanding.
